### ISSUE TITLE
Development resources (SDKs)

### ISSUE THREAD

**Issue by ghost** [aldostools/Resources#1]
I've prepared two github repos which provide pre-compiled PSL1GHT toolchains, tested to be working correctly:
- [SDK-Mirror](https://github.com/PS3SDK-Misc/SDK-Mirror): Mirrored and re-packaged pre-compiled toolchains from various authors.
- [SDK-Build](https://github.com/rhynec/PS3SDK-Build): Automated builds of the PSL1GHT toolchain, with the psdk variant meant as a re-creation of PSDK3v2 for Linux (using gcc 4), and the ps3dev-latest variant being a working build of latest ps3dev sources (using an older commit to PSL1GHT, since newer commits seem to break builds).

Are these resources appropriate for this repo?

**Comment by aldostools** [comment]
Thank you @rhynec for the SDKs. I find them very helpful for anyone that want to compile PS3 projects.

They look good, although I haven't tested them.  I will include them in the Resource page.

Thanks again for your contribution.

**Comment by ghost** [comment]
Thanks for the inclusion!
