### ISSUE TITLE
Multiman connection issue

### ISSUE THREAD

**Issue by ultimateshadsform** [aldostools/Resources#15]
Here is an example video I have the same issue.

https://www.youtube.com/watch?v=rW08HoR_4vs

It seems that multiman web was shut down or something? Is there a way to fix this?

Or does anyone have the files that the server ran?

**Comment by aldostools** [comment]
The official server was shutdown.
You can find various resources in https://github.com/aldostools/Resources/releases/tag/multiMAN

**Comment by ultimateshadsform** [comment]
Oh okay thanks! Seems to work nice!

**Comment by ultimateshadsform** [comment]
Just wondering when installing webman? Is there a way to disable FTP when I don't use it? Since I'm on a public network and anyone can access.
