### ISSUE TITLE
Can my project be posted here?

### ISSUE THREAD

**Issue by ohhsodead** [aldostools/Resources#3]
I have a simple and powerful mod manager that you might be interested to see.

https://github.com/ohhsodead/modio

Thanks.

**Comment by aldostools** [comment]
It's ok. Some mod users that don't know your project may find it useful.

Thanks for share the link.

**Comment by ohhsodead** [comment]
@aldostools Thank you. I have added the tool to a new section. Please let me know if it should be somewhere else.
