### ISSUE TITLE
PS2 Classics Launcher Copyright Protection

### ISSUE THREAD

**Issue by CreeperJuice** [aldostools/Resources#9]
Hello everyone,
I got some problems with the PS2 Classics Placeholder that I downloaded here. I installed the .pkg file, and after that, I launched the app, but I got these Copyright protection screens :
![image](https://user-images.githubusercontent.com/104071851/195989727-917bb44d-b2cd-40d9-b199-d3a9a6122a6e.png)
![image](https://user-images.githubusercontent.com/104071851/195989906-6da54e5b-b4f4-4643-8336-e810b4258614.png)
What I did wrong ?

**Comment by aldostools** [comment]
If you use HEN, you need to enable it or activate the rap file using Apollo or PSNpatch.

If you use Cobra, you need to enable Cobra. If you are on an old CFW, try updating to 4.84 or later.

**Comment by CreeperJuice** [comment]
I've just enabled Cobra, and I still get the same error.
For information, I'm on Evilnat 4.88.

**Comment by CreeperJuice** [comment]
I've just enabled Cobra, and I still get the same error.
For information, I'm on Evilnat 4.88.

**Comment by aldostools** [comment]
Try activating the RAP using Apollo or PSNpatch

NOTE: That the RAP only works for PS2 Classics converted using Aldo's PS2 Classics GUI.

If you're using an official PS2 game, you need to activate the RAP corresponding to the game

**Comment by CreeperJuice** [comment]
Sorry, I know that I'm a noob but what is a RAP file ? I've already seen it somewhere but I didn't understood what it was.

**Comment by aldostools** [comment]
You will find the option to activate the RAP for PS2 Classics in the aforementioned homebrews.

The RAP file is an universal key that is used to generate the Right Information File (RIF) needed by the NPDRM games (aka PKG games).

**Comment by CreeperJuice** [comment]
Ok, but where do I find this key ?

**Comment by aldostools** [comment]
If you bought the game, the key is activated automatically by the PSN Store.

If you're pirating the game, you have to find the key yourself or ask to your game providers.

**Comment by CreeperJuice** [comment]
Well I bought the game, but it's a real PS2 disk, and I want to convert it to play it on PS2 Classics since the game is blurred when I launch it with my PS3.

**Comment by CreeperJuice** [comment]
But I installed Apollo, and I don't see anything that mentions the RAP file.

**Comment by aldostools** [comment]
There is an option about PS2 Classics. Or activate the rap included in this ZIP.
[2P0001-PS2U10000_00-0000111122223333.zip](https://github.com/aldostools/Resources/files/9792511/2P0001-PS2U10000_00-0000111122223333.zip)

NOTE: This is my last reply. I will not be available until the next week.

EDIT:
If you're on CFW, you can mount the ISO without having to encrypt the game as PS2 Classics.

If you're on HEN, you will need to convert the ISO to PS2 Classics using Apollo.

**Comment by CreeperJuice** [comment]
Ok, it works, thanks.

**Comment by CreeperJuice** [comment]
Ok never mind. It works, but WMM has been uninstalled (don't know why) and I can't reinstall it since the installation of the installer (USB stick to PS3) always fails.
